--Таблица фильмов
CREATE TABLE IF NOT EXISTS film (
  film_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar  NOT NULL,
  description varchar,
  release_date date  NOT NULL,
  duration int,
  mpa_raiting varchar,
  CONSTRAINT pk_film PRIMARY KEY (film_id)
);

--Таблица пользователей
CREATE TABLE IF NOT EXISTS "user" (
  user_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email varchar NOT NULL,
  login varchar NOT NULL,
  name varchar,
  birthday date,
  CONSTRAINT pk_user PRIMARY KEY (user_id)
);

--Таблица лайков фильмов пользователями
CREATE TABLE IF NOT EXISTS likes (
  film_id int REFERENCES film (film_id) ON DELETE CASCADE NOT NULL,
  user_id int REFERENCES "user" (user_id) ON DELETE CASCADE NOT NULL,
  CONSTRAINT pk_likes PRIMARY KEY (film_id, user_id)
);

--Справочная таблица жанров фильмов
CREATE TABLE IF NOT EXISTS ganre (
  ganre_id int PRIMARY KEY NOT NULL,
  name varchar NOT NULL
);

--Таблица жанров, которым принадлежит фильм
CREATE TABLE IF NOT EXISTS film_ganre (
  film_id int REFERENCES film (film_id) ON DELETE CASCADE NOT NULL,
  ganre_id int REFERENCES ganre (ganre_id) ON DELETE CASCADE NOT NULL,
  CONSTRAINT pk_film_ganre PRIMARY KEY (film_id, ganre_id)
);

--Таблица дружеских связей между пользователями (парная запись означает подтверждение дружбы)
CREATE TABLE IF NOT EXISTS friends (
  user_id int REFERENCES "user" (user_id) ON DELETE CASCADE NOT NULL,
  friend_id int REFERENCES "user" (user_id) ON DELETE CASCADE NOT NULL,
  CONSTRAINT pk_friends PRIMARY KEY (user_id, friend_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_user_email ON "user"(email);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_login ON "user"(login);
CREATE UNIQUE INDEX IF NOT EXISTS idx_film_name_date ON film (name, release_date);
