CREATE TABLE IF NOT EXISTS film (
  film_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  description varchar,
  release_date date,
  duration int,
  mpa_raiting varchar
);

CREATE TABLE IF NOT EXISTS "user" (
  user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar,
  login varchar,
  name varchar,
  birthday date
);

CREATE TABLE IF NOT EXISTS likes (
  film_id int REFERENCES film (film_id),
  user_id int REFERENCES "user" (user_id),
  PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS ganre (
  ganre_id int PRIMARY KEY,
  name varchar
);

CREATE TABLE IF NOT EXISTS film_ganre (
  film_id int REFERENCES film (film_id),
  ganre_id int REFERENCES ganre (ganre_id),
  PRIMARY KEY (film_id, ganre_id)
);

CREATE TABLE IF NOT EXISTS friends (
  user_id int REFERENCES "user" (user_id),
  friend_id int REFERENCES "user" (user_id),
  PRIMARY KEY (user_id, friend_id)
);
